### ISSUE TITLE
upbit_api 코딩에서 plotly 실행 불가 오류

### ISSUE THREAD

**Issue by dkbs12** [ai-practice-course/yongseong-test#3]
4주차 강의에서 upbit_api 코딩 복습 중 plotly 이용한 그래프가 실행되지 않아서  yongseong-test 레퍼지토리에 제가 연습한 파일을 'upbit_apt_연습'이라는 이름의 파일로 업로드 하오니 검토해 주시기 바랍니다.  동 파일은 colab 환경에서 코딩 및 실행하였으나 plotly 그래프가 display 되지 않습니다.

**Comment by kion77** [comment]
어떤 오류인지 말씀해 주셔야 답변이 가능합니다.
colab에서는 plotly 그래프가 잘 보이지 않는 문제가 원래 있네요.

아래 사이트 참조하시기 바랍니다.

https://physikk.tistory.com/15

**Comment by dkbs12** [comment]
[https://github.com/ai-practice-course/yongseong-test/blob/main/upbit_api_%EC%97%B0%EC%8A%B5.ipynb](url)

**Comment by dkbs12** [comment]
안녕하세요,
아래 알려주신 링크 페이지에 나온대로 해봤지만 여전히 그래프가 보이지 않습니다.
issue 란에 colab 파일이 업로드 되지않아서 제 레퍼지토리의 코드 란에 해당 파일을 업로드 해 놓았습니다.
그런데 어차피 colab 환경에서 실행해 봐야 하므로 내일 다시 한 번 검토해 주시기 바랍니다.
 
손용성 배상
 
-----Original Message-----

**Comment by kion77** [comment]
COLAB 말고 제가 멘토링 시간에 드렸던 서버에서 작업해 보시면 될거 같습니다. 환경을 맞춰 놓은 부분이 있으니깐요. 훨씬 쉽게 하실 수 있지 않나 싶습니다.
